name: NestJS CI

#지정해둔 이벤트 발생 시 워크플로우 실행, 여기서는
#git push origin [main],그리고 main브랜치를 대상으로 하는 pr
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
#workflow에서 실행될 작업을 정의함
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # 프로젝트 디렉토리로 이동
            cd /home/ubuntu/LoadBlc

            # GitHub에서 최신 코드를 가져옴
            git pull

            # .env 파일 생성
            # echo "DB_NAME=${{ secrets.DB_NAME }}" > .env
            # echo "DB_SYNC=${{ secrets.DB_SYNC }}" >> .env
            # echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env

            source /home/ubuntu/.nvm/nvm.sh
            # 서버 실행 시크립트 가동!
            source ./run.sh
